apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.queueName }}
spec:
  ports:
  - name: {{ .Values.queueRole }}
    port: {{ .Values.queueNodePort }}
    targetPort: {{ .Values.queueNodePort }}
  selector:
    app: {{ .Values.app }}
    role: {{ .Values.queueRole }}
