apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webName }}
spec:
  ports:
    - name: {{ .Values.webService.name }}
      port: {{ .Values.webService.internalPort }}
      targetPort: {{ .Values.webService.externalPort }}
  selector:
    app: {{ .Values.app }}
    role: {{ .Values.webRole }}
  type: {{ .Values.webService.type }}